-- 1. Alter finance_entries to support Petty Cash Allocations
-- Safely add column only if it doesn't exist
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='finance_entries' AND column_name='is_petty_cash') THEN
        ALTER TABLE finance_entries ADD COLUMN is_petty_cash boolean DEFAULT false;
    END IF;
END $$;

-- 2. Create table for Petty Cash Expenses (Spending from the fund)
CREATE TABLE IF NOT EXISTS petty_cash_entries (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    user_id uuid references auth.users(id), -- Who entered this
    admin_id uuid, -- Organization owner (for filtering)
    description text not null,
    amount numeric not null, -- How much was spent
    date date not null default CURRENT_DATE,
    receipt_url text, -- Optional image
    category text -- e.g., Food, Travel, Office Supplies
);

-- 3. Enable RLS
ALTER TABLE petty_cash_entries ENABLE ROW LEVEL SECURITY;

-- 4. RLS Policies
-- Combined Select Policy: Admin OR Employee
DROP POLICY IF EXISTS "Users can view petty cash" ON petty_cash_entries;
CREATE POLICY "Users can view petty cash" ON petty_cash_entries FOR SELECT 
USING (
    ((select auth.uid()) = admin_id) OR  -- Is Admin
    ((select auth.uid())::text = admin_id::text) OR -- UUID text fallback
    EXISTS ( -- Is Employee
        SELECT 1 FROM users WHERE id = (select auth.uid()) AND admin_id = petty_cash_entries.admin_id
    )
);

-- Combined Insert Policy: Admin OR Employee
DROP POLICY IF EXISTS "Users can insert petty cash" ON petty_cash_entries;
CREATE POLICY "Users can insert petty cash" ON petty_cash_entries FOR INSERT 
WITH CHECK (
    ((select auth.uid()) = admin_id) OR
    ((select auth.uid())::text = admin_id::text) OR
    EXISTS (
        SELECT 1 FROM users WHERE id = (select auth.uid()) AND admin_id = petty_cash_entries.admin_id
    )
);

-- Delete Policy: Admin Only
DROP POLICY IF EXISTS "Admins can delete petty cash" ON petty_cash_entries;
CREATE POLICY "Admins can delete petty cash" ON petty_cash_entries FOR DELETE 
USING ((select auth.uid()) = admin_id OR (select auth.uid())::text = admin_id::text);

-- Cleanup old separate policies if they exist (to be safe)
DROP POLICY IF EXISTS "Admins can view all petty cash" ON petty_cash_entries;
DROP POLICY IF EXISTS "Admins can insert petty cash" ON petty_cash_entries;
DROP POLICY IF EXISTS "Employees can view their org's petty cash" ON petty_cash_entries;
DROP POLICY IF EXISTS "Employees can add petty cash entries" ON petty_cash_entries;

-- Grant permissions
GRANT ALL ON petty_cash_entries TO authenticated;
GRANT ALL ON petty_cash_entries TO service_role;
